### ISSUE TITLE
jobSubmit fails with "errorMessage": "[object Object]"

### ISSUE THREAD

**Issue by stevebanik** [aws-solutions/video-on-demand-on-aws-foundations#17]
This occurs when the .mp4 file is uploaded to the source S3 bucket.  It also fails with the same error when testing in the Lambda function with S3.

**Comment by stevebanik** [comment]
Hi @eggoynes thanks for your reply.  I was able to workaround the error by uploading the media to the assets01 subdir instead of the root dir of the bucket.  I don't recall seeing that mentioned in the documentation, but it worked for me.

**Comment by eggoynes** [comment]
Thank you Steve for the feedback. We will make sure to make the documentation more clear. We should state that the media assets have to be placed into the assets01 subdirectory. I believe you are also able to make other folders if you want to keep certain media separate for organizational purposes.
