### ISSUE TITLE
Custom Resource failed to stabilize in expected time

### ISSUE THREAD

**Issue by benm5678** [aws-solutions/video-on-demand-on-aws-foundations#4]
Trying to deploy it with CDK and after it hangs for an hour trying to deploy the Custom Resource, it gives this error: "Custom Resource failed to stabilize in expected time."

**Comment by morjoan** [comment]
Hi, trying to replicate issue at our end. Will get back to you when we have findings.  Thanks!

**Comment by morjoan** [comment]
What seems to be happening is that when you deploy via CDK, the library dependencies are not being packaged up with the Lambda functions automatically. The installation of the custom resources fails to find expected modules. 
You will need to run `npm install` both in the _source/custom-resource_ and the _source/job-submit_ directories. Then run deploy. We'll update our documentation in the next release. Hope this gets you unblocked.

**Comment by benm5678** [comment]
Thanks a lot for fast reply!!!  That solution worked. 
I wonder if there is anyway to adjust the timeout, so in case of errors doesn't take 2 hrs.

**Comment by eggoynes** [comment]
Added in the v1.1.0 release.
